name: SDKMAN! Vendor Release Action
description: Release new Candidate versions via SDKMAN!'s Vendor API.
inputs:
  consumer-key:
    description: The unique identifier of the Consumer
    required: true
  consumer-token:
    description: The API token of the Consumer
    required: true
  candidate:
    description: The name of the Candidate to release
    required: true
  version:
    description: The version of the Candidate to release
    required: true
  url:
    description: The URL pointing to the binary
    required: true
runs:
  using: 'composite'
  steps:
    - id: sdkman-vendor
      shell: bash
      run: |
        curl -X POST \
        -H 'Consumer-Key: ${{inputs.consumer-key}}' \
        -H 'Consumer-Token: ${{inputs.consumer-token}}' \
        -H 'Content-Type: application/json' \
        -d '{"candidate": "${{inputs.candidate}}", "version": "${{inputs.version}}", "url": "${{inputs.url}"}}' \
        https://vendors.sdkman.io/release
